<script type="text/javascript">
    require([
        'jquery',
        'minicolors',
        'minminicolors'
    ], function ($) {
        $(document).ready(function($) {
			loadMinicolor();
			$('button.action-add').on('click', function () {
				loadMinicolor();
			});
			$('table').delegate('button.action-add', 'click', function () {
				loadMinicolor();
			});
		});
		function loadMinicolor() {
			$('.color').each(function () {
				$(this).minicolors({
					control: $(this).attr('data-control') || 'hue',
					defaultValue: $(this).attr('data-defaultValue') || '',
					format: $(this).attr('data-format') || 'hex',
					keywords: $(this).attr('data-keywords') || '',
					inline: $(this).attr('data-inline') === 'true',
					letterCase: $(this).attr('data-letterCase') || 'lowercase',
					opacity: $(this).attr('data-opacity'),
					position: $(this).attr('data-position') || 'bottom left',
					swatches: $(this).attr('data-swatches') ? $(this).attr('data-swatches').split('|') : [],
					change: function (value, opacity) {
						if (!value) return;
						if (opacity) value += ', ' + opacity;
						if (typeof console === 'object') {
							console.log(value);
						}
					},
				});

			});
		}
    });
</script>

