<script>
    require(["jquery", 'underscore', 'Magento_Ui/js/modal/modal'], function ($, _, modal) {
        $(document).ready(function() {
            $('.reviews-actions a').attr('target', '_parent');
            $('.product-social-links a').attr('target', '_parent');

        });

        /** Events listener **/
        $(document).on('ajaxComplete', function (event, xhr, settings) {
            var parentBody = window.parent.document.body;
            var cartMessage = false;
            var showShoppingCheckoutButtons  = parseInt(window.vicomage_quickview.showShoppingCheckoutButtons);
            if (settings.type.match(/get/i) && _.isObject(xhr.responseJSON)) {
                var result = xhr.responseJSON;
                if (_.isObject(result.messages)) {
                    var messageLength = result.messages.messages.length;
                    var message = result.messages.messages[0];
                    if (messageLength && message.type == 'success') {
                        cartMessage = message.text;
                    }
                }
                if (_.isObject(result.cart) && _.isObject(result.messages)) {
                    var messageLength = result.messages.messages.length;
                    var message = result.messages.messages[0];
                    if (messageLength && message.type == 'success') {
                        cartMessage = message.text;
                    }
                }

                if  (cartMessage) {
                    window.parent.vicomage_quickview.showMiniCartFlag = true;
                }


                if (showShoppingCheckoutButtons && cartMessage) {
                    $('<div />').html('')
                        .modal({
                            title: cartMessage,
                            autoOpen: true,
                            buttons: [{
                                text: $.mage.__('Continue Shopping'),
                                attr: {
                                    'data-action': 'confirm'
                                },
                                'class': 'action primary',
                                click: function () {
                                    this.closeModal();
                                }
                            },
                                {
                                    text: $.mage.__('Go To Checkout'),
                                    attr: {
                                        'data-action': 'cancel'
                                    },
                                    'class': 'action primary',
                                    click: function () {
                                        parent.window.location = '<?php echo $block->getUrl('checkout', ['_secure' => true]);?>'
                                    }
                                }]
                        });
                }

            }
        });
    });
</script>