<?php $config = $block->getConfig(); ?>
<?php if ($config['enabled'] && isset($config['group'])): ?>
    <?php
    $items = $block->getItems();
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    ?>
	<div class="sections vertical-menu">
		<div class="block-title">
			<h4 class="title"><i class="fa fa-bars"></i>Catagories</h4>
		</div>
		<nav class="vertical vicomage-megamenu navigation" role="vertical">
			<ul id="verticalMenu" class="nav nav-main">
				<?php if ($config['show_home']): ?>
					<li class="ui-menu-item level0 dropdown link-home<?php if ($config['show_home_demo']): ?> parent<?php endif; ?>">
						<a href="<?php echo $storeManager->getStore()->getBaseUrl(); ?>"
						   class="level-top"><span><?php echo __('Home') ?></span></a>
						<?php if ($config['show_home_demo']): ?>
							<div class="open-children-toggle"></div>
							<?php echo $this->getChildHtml("home.store_switcher"); ?>
						<?php endif; ?>
					</li>
				<?php endif; ?>

				<?php echo $block->getCategorys(); ?>

				<?php foreach ($items as $item) {
					echo $block->getMegamenuHtml($item);
				} ?>
			</ul>
		</nav>
	</div>
    <script type="text/javascript">
        require([
            'jquery',
            'megamenu'
        ], function ($) {
            $(".vicomage-megamenu").Megamenu();
        });
    </script>
<?php endif; ?>

