<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')):?>
<?php
    $vico_helper = $this->helper('Vicomage\General\Helper\Data');
    $_helper = $this->helper('Vicomage\General\Helper\Customtabs');
    $product_config = $vico_helper->getConfig('vicomage_general_config/product');
    $tab_style = "";
    if(isset($product_config['tab_style']) && $product_config['tab_style'])
        $tab_style = $product_config['tab_style'];
?>
    <div class="product info detailed <?php echo $tab_style; ?>">
        <?php $layout = $block->getLayout(); ?>
 <?php if(!$tab_style || $tab_style != "vertical"): ?>
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <?php foreach ($detailedInfoGroup as $name):?>
                <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                ?>
                <div class="data item title"
                     aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title"
                     data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#<?php /* @escapeNotVerified */ echo $alias; ?>"
                       id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title">
                        <?php /* @escapeNotVerified */ echo $label; ?>
                    </a>
                </div>
                <div class="data item content" id="<?php /* @escapeNotVerified */ echo $alias; ?>" data-role="content">
                    <?php /* @escapeNotVerified */ echo $html; ?>
                </div>
            <?php endforeach;?>
            <?php
                if($custom_cms_tabs = $_helper->getCustomTabs($block->getProduct())) {
                    $i = 1;
                    foreach($custom_cms_tabs as $_item) {
            ?>
                <div class="data item title"
                     aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo "custom-".$i;?>-title"
                     data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo "custom-".$i;?>">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#<?php /* @escapeNotVerified */ echo "custom-".$i; ?>"
                       id="tab-label-<?php /* @escapeNotVerified */ echo "custom-".$i;?>-title">
                        <?php /* @escapeNotVerified */ echo $_item['tab_title']; ?>
                    </a>
                </div>
                <div class="data item content" id="<?php /* @escapeNotVerified */ echo "custom-".$i; ?>" data-role="content">
                    <?php /* @escapeNotVerified */ echo $_item['tab_content']; ?>
                </div>
            <?php
                        $i++;
                    }
                }
            ?>
        </div>
        <?php elseif($tab_style && $tab_style == "vertical"): ?>
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
			 
				<div class="items-tabs">
					 <?php foreach ($detailedInfoGroup as $name):?>
						<?php
							$html = $layout->renderElement($name);
							if (!trim($html)) {
								continue;
							}
							$alias = $layout->getElementAlias($name);
							$label = $block->getChildData($alias, 'title');
							$alias = str_replace(".","_",$alias);
						?>
						 <div class="data item title"
								 aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title"
								 data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>">
								<a class="data switch"
								   tabindex="-1"
								   data-toggle="switch"
								   href="#<?php /* @escapeNotVerified */ echo $alias; ?>"
								   id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title">
									<?php /* @escapeNotVerified */ echo $label; ?>
								</a>
							</div>

					<?php endforeach;?>
					<?php
						if($custom_cms_tabs = $_helper->getCustomTabs($block->getProduct())) {
							$i = 1;
							foreach($custom_cms_tabs as $_item) {
					?>
						<div class="data item title"
							 aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo "custom-".$i;?>-title"
							 data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo "custom-".$i;?>">
							<a class="data switch"
							   tabindex="-1"
							   data-toggle="switch"
							   href="#<?php /* @escapeNotVerified */ echo "custom-".$i; ?>"
							   id="tab-label-<?php /* @escapeNotVerified */ echo "custom-".$i;?>-title">
								<?php /* @escapeNotVerified */ echo $_item['tab_title']; ?>
							</a>
						</div>
					<?php
								$i++;
							}
						}
					?>
				
				</div>
				<div class="data-tabs-content">
					 <?php foreach ($detailedInfoGroup as $name):?>
						<?php
							$html = $layout->renderElement($name);
							if (!trim($html)) {
								continue;
							}
							$alias = $layout->getElementAlias($name);
							$label = $block->getChildData($alias, 'title');
							$alias = str_replace(".","_",$alias);
						?>
						<div class="data item content" id="<?php /* @escapeNotVerified */ echo $alias; ?>" data-role="content">
							<?php /* @escapeNotVerified */ echo $html; ?>
						</div>
					<?php endforeach;?>
					<?php
						if($custom_cms_tabs = $_helper->getCustomTabs($block->getProduct())) {
							$i = 1;
							foreach($custom_cms_tabs as $_item) {
					?>
						<div class="data item content" id="<?php /* @escapeNotVerified */ echo "custom-".$i; ?>" data-role="content">
							<?php /* @escapeNotVerified */ echo $_item['tab_content']; ?>
						</div>
					<?php
								$i++;
							}
						}
					?>
				</div>    
        </div>
        <?php endif; ?>
    </div>
<?php endif; ?>
<?php if(isset($product_config['move_tab']) && $product_config['move_tab']): ?>
<script type="text/javascript">
require([
    'jquery'
], function ($) {
    $(document).ready(function(){
        $(".product.info.detailed").detach().appendTo($(".product-info-main"));
    });
});
</script>
<?php endif; ?>