<?php
if(!$this->getEnabled()) return;
$selector = 'vicomage-'.rand(0,999999999).date('YmdHis');
$brands = $this->getBrands();
if(!count($brands)) return;
?>
<div class="<?php echo $selector ?>">
    <?php echo $this->getTitle() ? '<h2 class="title item">' . '<span>' . $this->getTitle() . '</span>' . '</h2>' : '' ?>
    <div class="shopbrand">
        <?php $i=0; foreach ($brands as $brand) :?>
			<div class="item">
				<a href="<?php echo $this->getUrlBrand($brand) ?>">
					<img class="brand img-responsive" src="<?php echo $this->getImage($brand)?>" alt="<?php echo __($brand->getTitle()) ?>" title="<?php echo __($brand->getTitle()) ?>" />
				</a>
			</div>
        <?php endforeach ?>
    </div>
</div>

<script type="text/javascript">
    require([
        'jquery',
        'vicomagecore',
        ], function($){
            (function($) {
                var shopbrand = $('.<?php echo $selector ?> .shopbrand');
                var config = '<?php echo $this->getFrontendCfg();?>';
                $.fn.vicomageSlider(shopbrand,config);
            })(jQuery);
    });
</script>

