<?php
use Magento\Framework\App\Action\Action;
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$FormKey = $objectManager->get('Magento\Framework\Data\Form\FormKey');
$_productCollection = $block->getLoadedProductCollection();
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
$themeHelper = $this->helper('Vicomage\General\Helper\Data');
$multiWidgetHelper = $this->helper('Vicomage\Multiwidget\Helper\Data');

?>
<div class="product-type-group product_type_<?php echo $this->getTypeFilter(); ?>">
    <?php if (!$_productCollection->count()): ?>
        <div class="message info empty">
            <div>
                <?php echo __('We can\'t find products matching the selection.') ?>
            </div>
        </div>
    <?php else: ?>
    <?php
    $viewMode = 'grid';
    $image = 'category_page_grid';
    $hover_image = 'category_page_grid-hover';
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $pos = $block->getPositioned();
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $_helper = $objectManager->get('\Magento\Catalog\Helper\Output');
    $config = $this->getWidgetCfg();
    ?>
            <div class="columns-container full-page-container">
                <?php $i=1; foreach ($_productCollection as $_product): ?>
                    <div class="section product-item">
						<div class="section-product-featured">
						<div class="tv-table">
							<?php if ($i % 2 == 1) { ?>
								<div class="tv-tablecell tv-tablecell-1">
									<div class="block-image effect">
										<a href="<?php /* @escapeNotVerified */
											echo $_product->getProductUrl() ?>" class="image-wrap"
											   tabindex="-1">
												<?php
												$productImage = $_imagehelper->init($_product, $image)->resize($config['width-image'], $config['height-image']);
												$productImageUrl = $productImage->getUrl();
												?>
												<img class="img-responsive" src="<?php echo $productImageUrl; ?>"
													 alt="<?php echo $productImage->getLabel(); ?>"/>
											</a>
									</div>
								</div>
							<?php } ?>
							<div class="tv-tablecell tv-tablecell-2">
								<div class="box-html block">
									<strong class="product name product-item-name">
										<a class="product-item-link"
										   href="<?php echo $_product->getProductUrl() ?>">
											<?php echo $_helper->productAttribute($_product, $_product->getName(),
												'name'); ?>
										</a>
									</strong>
									
									<?php if(isset($config['review'])): ?>
										<?php
											$review_html = $block->getReviewsSummaryHtml($_product, $templateType);
										?>
										<?php if($review_html): ?>
											<?php echo $review_html; ?>
										<?php else: ?>
										<div class="product-reviews-summary short">
											<div class="rating-summary">
												<span class="label"><span>Rating:</span></span>
												<div class="rating-result" title="0%">
													<span style="width:0"><span>0%</span></span>
												</div>
											</div>
										</div>
										<?php endif; ?>
									<?php endif; ?>
										
									<?php echo $block->getProductPrice($_product) ?>
									<?php echo $block->getProductDetailsHtml($_product); ?>

									<div class="block-content">
										<p> 
										<?php if ($_product->getShortDescription()):?>
											<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
										<?php endif; ?>
										</p>
									</div>
									<div class="product-item-inner">
										<?php
										 if(isset($config['timer'])) {
											echo $multiWidgetHelper->getTimer($_product);
										}?>
										<?php if (isset($config['wishlist']) || isset($config['compare']) || isset($config['cart']) || isset($config['quickview'])): ?>
											<div class="product actions product-item-actions">
												<?php if (isset($config['cart'])): ?>
													<div class="actions-primary-none"<?php echo strpos($pos,
														$viewMode . '-primary') ? $position : ''; ?>>
														<?php if ($_product->isSaleable()): ?>
															<?php $postParams = $block->getAddToCartPostParams($_product); ?>
															<form data-role="tocart-form"
																  action="<?php echo $postParams['action']; ?>"
																  method="post">
																<input type="hidden" name="product"
																	   value="<?php echo $postParams['data']['product']; ?>">
																<input type="hidden"
																	   name="<?php echo Action::PARAM_NAME_URL_ENCODED; ?>"
																	   value="<?php echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
																<input name="form_key" type="hidden" value="<?php echo $FormKey->getFormKey();?>">
																<button type="submit"
																		title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
																		class="action primary button btn-cart pull-left-none">
																	<span><?php echo __('Add to Cart') ?></span>
																</button>
															</form>
														<?php else: ?>
															<?php if ($_product->getIsSalable()): ?>
																<div class="stock available">
																	<span><?php echo __('In stock') ?></span></div>
															<?php else: ?>
																<div class="stock unavailable">
																	<span><?php echo __('Out of stock') ?></span></div>
															<?php endif; ?>
														<?php endif; ?>
														<a class="view-detail" href="<?php echo $_product->getProductUrl() ?>">
															<?php echo __('View Detail') ?>
														</a>
													</div>
												<?php endif; ?>
												 <?php if (isset($config['wishlist']) || isset($config['compare']) || isset($config['quickview'])): ?>
													<div class="actions-secondary add-to-links">
														<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && isset($config['wishlist'])): ?>
															<a href="#"
															   class="action towishlist"
															   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
															   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
															   data-post='<?php echo $block->getAddToWishlistParams($_product); ?>'
															   data-action="add-to-wishlist"
															   role="button">
																<span><?php echo __('Add to Wish List') ?></span>
															</a>
														<?php endif; ?>
														<?php if (isset($config['compare'])):
															$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
															?>
															<a href="#"
															   class="action tocompare"
															   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
															   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
															   data-post='<?php echo $compareHelper->getPostDataParams($_product); ?>'
															   role="button">
																<span><?php echo __('Add to Compare') ?></span>
															</a>
														<?php endif; ?>
														<?php if(isset($config['quickview'])) :?>
															<a class="vicomage-quickview btn-quickview"
															   data-quickview-url="<?php echo $this->getUrl('vicomage_quickview/catalog_product/view/'); ?>id/<?php echo $_product->getId(); ?>"
															   href="javascript:void(0);"><span><i
																		class="fa fa-search"></i></span></a>
														<?php endif;?>
													</div>
												<?php endif; ?>
											</div>
										<?php endif; ?>
									</div>
								</div>
							</div>
							<?php if ($i % 2 == 0) { ?>
								<div class="tv-tablecell tv-tablecell-1">
									<div class="block-image effect">
										<a href="<?php /* @escapeNotVerified */
											echo $_product->getProductUrl() ?>" class="image-wrap"
											   tabindex="-1">
												<?php
												$productImage = $_imagehelper->init($_product, $image)->resize($config['width-image'], $config['height-image']);
												$productImageUrl = $productImage->getUrl();
												?>
												<img class="img-responsive" src="<?php echo $productImageUrl; ?>"
													 alt="<?php echo $productImage->getLabel(); ?>"/>
											</a>
									</div>
								</div>
							<?php } ?>
						</div>
						</div>
						
                    </div>
                <?php $i++; endforeach; ?>
            </div>
        <?php if (!$block->isRedirectToCartEnabled()) : ?>
            <script type="text/x-magento-init">
                {
                    "[data-role=tocart-form], .form.map.checkout": {
                        "catalogAddToCart": {}
                    }
                }
            </script>
        <?php endif; ?>

        <?php
        if(isset($config['timer']) && $config['timer'] && $config['timer_type']) :
            $layout = '<span class="day">%%D%%</span><span class class="colon">:</span><span class="hour">%%H%%</span><span class="colon">:</span><span class="min">%%M%%</span><span class="colon">:</span><span class="sec">%%S%%</span>';
            if($config['timer_type'] == 2){
                $layout = '<div class="timer-box"><span class="day">%%D%%</span><span class="title">' . __('Days') . '</span></div><div class="timer-box"><span class="hour">%%H%%</span><span class="title">' . __('Hrs')  . '</span></div><div class="timer-box"><span class="min">%%M%%</span><span  class="title">' . __('Mins') . '</span></div><div class="timer-box"><span class="sec">%%S%%</span><span  class="title">' . __('Secs') . '</span></div>';
            }
            ?>
            <script type="text/javascript">
                var vicommage_timer_layout 	= '<?php echo $layout ?>';
                var vicommage_timer_timeout = '<span class="timeout"><?php echo __('Time out!')?></span>';
            </script>
        <?php endif; ?>
    <?php endif; ?>
</div>
