<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
    $vico_helper = $this->helper('Vicomage\General\Helper\Data');
    $popup = $vico_helper->getConfig('vicomage_general_config/newsletter');
    if($popup['enable']) {
        $delay = $popup["delay"];
?>
<script type="text/javascript">
require([
        'jquery',
        'fancybox',
        'jquery/jquery.cookie'
    ], function ($) {
        $(document).ready(function(){
        <?php if($popup['enable'] == 1): ?>
            if($("body").hasClass("cms-index-index")) {
        <?php endif; ?>
                var check_cookie = $.cookie('newsletter-popup');
                if(window.location!=window.parent.location){
                    $('#newsletter-popup').remove();
                } else {
                    if(check_cookie == null || check_cookie == 'shown') {
                        setTimeout(function(){
                            beginNewsletterForm();
                        }, <?php echo $delay; ?>);
                    }
                    $('#newsletter_popup_dont_show_again').on('change', function(){
                        if($(this).length){        
                            var check_cookie = $.cookie('newsletter-popup');
                            if(check_cookie == null || check_cookie == 'shown') {
                                $.cookie('newsletter-popup','dontshowitagain');            
                            }
                            else
                            {
                                $.cookie('newsletter-popup','shown');
                                beginNewsletterForm();
                            }
                        } else {
                            $.cookie('newsletter-popup','shown');
                        }
                    });
                }
        <?php if($popup['enable'] == 1): ?>
            }
        <?php endif; ?>
        });
        
        function beginNewsletterForm() {
            $.fancybox({
                'padding': '0px',
                'transitionIn': 'fade',
                'transitionOut': 'fade',
                'centerOnScroll': true,
                'type': 'inline',
                'href': '#newsletter-popup',
                'onComplete': function() {
                    $.cookie('newsletter-popup', 'shown');
                },
                'tpl': { 
                    closeBtn: '<a title="Close" class="fancybox-item fancybox-close fancybox-newsletter-close" href="javascript:;"></a>' 
                },
                'helpers': {
                    overlay: {
                        locked: false
                    }
                }
            });
            $('#newsletter-popup').trigger('click');
        }
});
</script>
<style type="text/css">
#newsletter-popup{
<?php
    if($popup["width"]){
        echo "width:".$popup["width"].";";
    }
    if($popup["height"]){
        echo "height:".$popup["height"].";";
    }
    if(isset($popup["bg_image"]) && $popup["bg_image"]){
        $folderName = \Vicomage\General\Model\Config\Backend\Image\Newsletterbg::UPLOAD_DIR;
        $path = $folderName . '/' . $popup["bg_image"];
        $imageUrl = $vico_helper->getBaseUrl() . $path;
?>
    background-image:url(<?php echo $imageUrl;?>);
<?php
    }
?>
}
</style>
<div class="newsletter" id="newsletter-popup" style="display: none;">
    <div class="block-popup-subscribe">
		<div class="newsletter-popup-content">
			<?php echo $popup["content"]; ?>
			<div class="block block-subscribe">
				<form class="form subscribe"
					novalidate
					action="<?php echo $block->getFormActionUrl() ?>"
					method="post"
					data-mage-init='{"validation": {"errorClass": "mage-error"}}'
					id="newsletter-validate-detail">
					<div class="field newsletter">
						<div class="control">
							<input name="email" placeholder="Enter your email address" type="email" id="newsletter-popup-form"
										data-validate="{required:true, 'validate-email':true}"/>
						</div>
					</div>
					<div class="actions">
						<button class="action subscribe primary" title="<?php echo __('Subscribe') ?>" type="submit">
							<span><?php echo __('Subscribe!') ?></span>
						</button>
					</div>
				</form>
			</div>
        </div>
		<div class="subscribe-bottom">
			<input type="checkbox" id="newsletter_popup_dont_show_again"/>
			<label for="newsletter_popup_dont_show_again"><?php echo __("Don't show this popup again"); ?></label>
		</div>
    </div>
</div>
<?php
    }
?>
