<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<form class="form subscribe"
	  novalidate
	  action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
	  method="post"
	  data-mage-init='{"validation": {"errorClass": "mage-error"}}'
	  id="newsletter-validate-detail">
	<div class="input-newleter">
		<input name="email" type="email" id="newsletter"
			   placeholder="<?php /* @escapeNotVerified */ echo __('Email Sign up') ?>"
			   data-validate="{required:true, 'validate-email':true}"/>
		<div class="actions">
			<button class="action subscribe primary" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
				<span><?php /* @escapeNotVerified */ echo __('Subscribe') ?></span>
			</button>
		</div>
	</div>

</form>



   
