<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Currency switcher
 *
 * @see \Magento\Directory\Block\Currency
 */
?>
<?php if ($block->getCurrencyCount() > 1): ?>
<?php $currencies = $block->getCurrencies(); ?>
<?php $currentCurrencyCode = $block->getCurrentCurrencyCode(); ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : ''?>
<div class="switcher currency switcher-currency" id="switcher-currency<?php /* @escapeNotVerified */ echo $id?>">
	<?php if(!$this->helper('Vicomage\General\Helper\Data')->getConfig('vicomage_general_config/header/currency_short')){ ?>
		 <ul class="currency-list">
			<?php foreach ($currencies as $_code => $_name): ?>
				<?php $_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
					  $_Symbol = $_objectManager->create('Magento\Directory\Model\CurrencyFactory')->create()->load($_code); ?>
				<li class="currency-<?php /* @escapeNotVerified */ echo $_code ?> switcher-option <?php if ($_code == $currentCurrencyCode): ?>active<?php endif; ?>">
					<a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getSwitchCurrencyPostData($_code); ?>'>
					<?php echo $_Symbol->getCurrencySymbol(); ?>
					</a>
				</li>
			<?php endforeach; ?>
		</ul>
	<?php } else { ?>
		<div class="actions dropdown options switcher-options">
			<div class="action toggle switcher-trigger" id="switcher-currency-trigger<?php /* @escapeNotVerified */ echo $id?>">
				<strong class="language-<?php echo $block->escapeHtml($block->getCurrentCurrencyCode()) ?>">
					 <span><?php echo $block->escapeHtml($currentCurrencyCode) ?><?php if(!$this->helper('Vicomage\General\Helper\Data')->getConfig('vicomage_general_config/header/currency_short')): ?> - <?php echo @$block->escapeHtml($currencies[$currentCurrencyCode]) ?><?php endif; ?></span>
				</strong>
			</div>
			<ul class="dropdown switcher-dropdown" data-mage-init='{"dropdownDialog":{
				"appendTo":"#switcher-currency<?php /* @escapeNotVerified */ echo $id?> > .options",
				"triggerTarget":"#switcher-currency-trigger<?php /* @escapeNotVerified */ echo $id?>",
				"closeOnMouseLeave": false,
				"triggerClass":"active",
				"parentClass":"active",
				"buttons":null}}'>
				<?php foreach ($currencies as $_code => $_name): ?>
					<?php if ($_code != $currentCurrencyCode): ?>
						<li class="currency-<?php /* @escapeNotVerified */ echo $_code ?> switcher-option">
							<a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getSwitchCurrencyPostData($_code); ?>'><?php /* @escapeNotVerified */ echo $_code ?> - <?php /* @escapeNotVerified */ echo $_name ?></a>
						</li>
					<?php endif; ?>
				<?php endforeach; ?>
			</ul>
		</div>
	<?php } ?>
</div>
<?php endif; ?>
