<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<form class="form contact"
      action="<?php echo $block->getFormAction(); ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?php echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
		<div class="row">
        <fieldset class="fieldset ">
            <div class="fields contact-fields-left col-sm-12">
				<div class="row">
					<div class="col-sm-6">
						<div class="field name required">
							<div class="control">
								<input placeholder="<?php echo __('Name') ?>" name="name" id="name" title="<?php echo __('Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
							</div>
						</div>
					</div>
					<div class="col-sm-6">
						<div class="field email required">
							<div class="control">
								<input placeholder="<?php echo __('Email') ?>" name="email" id="email" title="<?php echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
							</div>
						</div>
					</div>
				</div>
				<div class="field telephone">
					<div class="control">
						<input placeholder="<?php echo __('Phone Number') ?>" name="telephone" id="telephone" title="<?php echo __('Phone Number') ?>" value="" class="input-text" type="text" />
					</div>
				</div>
				<div class="field comment required">
					<div class="control">
						<textarea placeholder="<?php echo __('What is on your mind?') ?>" name="comment" id="comment" title="<?php echo __('What’s on your mind?') ?>" class="input-text" cols="5" rows="8" data-validate="{required:true}"></textarea>
					</div>
				</div>
				<?php echo $block->getChildHtml('form.additional.info'); ?>
            </div>
        </fieldset>
		</div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?php echo __('Submit') ?>" class="action submit primary">
                <span><?php echo __('Submit') ?></span>
            </button>
        </div>
    </div>
</form>
