<?php
	$vico_helper = $this->helper('Vicomage\General\Helper\Data');
    $contacts_config = $vico_helper->getConfig('vicomage_general_config/contacts');
    $_enable = $contacts_config['enable'];
    if($_enable){
        $_apikey = $contacts_config['api_key'];
        $_full_width = $contacts_config['full_width'];
        $_address = $contacts_config['address'];
        $_zoom = $contacts_config['zoom'];
        $_center_lat = $contacts_config['latitude'];
        $_center_lng = $contacts_config['longitude'];
        
?>
<?php if(!$contacts_config['mapiframe']): ?>
<script type="text/javascript" src="//maps.googleapis.com/maps/api/js?<?php if($_apikey): ?>key=<?php echo $_apikey; ?><?php else: ?>v=3.17<?php endif; ?>"></script>
<script type="text/javascript">
    function initialize() {
        var pos = new google.maps.LatLng(<?php echo $_center_lat; ?>, <?php echo $_center_lng; ?>);
        var mapOptions = {
            center: pos,
            panControl: true,
            zoomControl: true,
            mapTypeControl: true,
            scaleControl: true,
            streetViewControl: true,
            overviewMapControl: true,
            zoom: <?php echo $_zoom; ?>
        };
        var map = new google.maps.Map(document.getElementById("store_map"), mapOptions);
        var marker = new google.maps.Marker({
            position: pos,
            map: map,
            title: '<?php echo $_address; ?>'
        });
    }
    google.maps.event.addDomListener(window, 'load', initialize);
</script>
<?php endif; ?>
<div class="contact-map">
	<?php if(!$_full_width): ?>
	<div class="container">
	<?php endif; ?>
		<?php if($contacts_config['mapiframe']){ ?>
			<?php echo $contacts_config['mapiframe_content']; ?>
		<?php } else { ?>
			<div id="store_map" style="min-height: 300px; width: 100%;"></div>
		<?php } ?>
	<?php if(!$_full_width): ?>
	</div>
	<?php endif; ?>
</div>
<?php
    }
?>