<?php $config = $block->getConfig(); ?>
<?php if ($config['enabled'] && isset($config['group'])): ?>
    <?php
    $items = $block->getItems();
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    ?>
    <div class="accordion-container block">
        <nav class="accordion accordion-megamenu-top" role="navigation">
            <ul id="mainMenu" class=" nav-main">
				<?php if ($this->getChildHtml("accordion.store_switcher")): ?>
				<li class="ui-menu-item level0 dropdown link-home parent">
					<a href="<?php echo $storeManager->getStore()->getBaseUrl(); ?>"
					   class="level-top"><span><?php echo __('Home') ?></span></a>
					<?php echo $this->getChildHtml("accordion.store_switcher"); ?>
				</li>
				<?php endif; ?>
                <?php echo $block->getCategorys(); ?>
				<?php if ($items) : ?>
                <?php foreach ($items as $item) {
                    echo $block->getMegamenuHtml($item);
                } ?>
				 <?php endif; ?>
            </ul>
        </nav>
    </div>

    <script type="text/javascript">
        require([
            'jquery',
            'navaccordion'
        ], function ($) {
            $(".accordion-megamenu-top").navAccordion({
                expandButtonText: '<i class="fa fa-angle-down"></i>',  //Text inside of buttons can be HTML
                collapseButtonText: '<i class="fa fa-angle-up"></i>'
            });
        });

    </script>
<?php endif; ?>

