<?php
/**
 * Blog post list item template
 *
 * @var $block \Vicomage\Blog\Block\Post\AbstractPost
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
?>
<li class="post-holder post-holder-<?php echo $_post->getId() ?>">

    <div class="post-content">
        <div class="post-description clearfix">
            <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
            <div class="post-image">
                <a href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                    <img src="<?php echo $featuredImage ?>" alt="<?php echo $_postName ?>" />
                </a>
                <div class="post-date">
                    <?php // echo $_post->getPublishDate('j, n, Y') ?>
                    <span class="date-home-day"><?php echo $_post->getPublishDate('j') ?></span>
                    <span class="date-home-month"><?php echo $_post->getPublishDate('M') ?></span>
                </div>
            </div>
            <?php } ?>
            <div class="post-title-holder clearfix">
                <h2 class="post-title">
                    <a class="post-item-link"
                       href="<?php echo $_postUrl ?>">
                        <?php echo $_postName; ?>
                    </a>
                </h2>

                <div class="addthis_toolbox addthis_default_style" addthis:url="<?php echo $_postUrl ?>">
                    <a class="addthis_button_facebook"></a>
                    <a class="addthis_button_twitter"></a>
                    <a class="addthis_button_email"></a>
                    <a class="addthis_button_compact"></a>
                </div>
            </div>

            <?php echo $this->getInfoHtml() ?>
            <div class="post-text-hld clearfix">
                <?php echo $block->getShorContent() ?>
            </div>
            <a class="post-read-more" href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>"
               >
               <?php echo __('Read more') ?>
            </a>
        </div>
    </div>
    <div class="post-footer">

    </div>
</li>