<?php
/**
 * Blog post og:tags
 *
 * @var $block \Vicomage\Blog\Block\Post\View\Opengraph
 */
?>

<meta property="og:type" content="<?php echo $block->getType(); ?>" />
<meta property="og:title" content="<?php echo $block->getTitle(); ?>" />
<meta property="og:description" content="<?php echo $block->getDescription(); ?>" />
<meta property="og:url" content="<?php echo $block->getPageUrl(); ?>" />
<?php if ($image = $block->getImage()) { ?>
<meta property="og:image" content="<?php echo $image; ?>" />
<?php } ?>